<?php
/**
 * Tests for future exception reconciliation.
 *
 * @package MiMe\WPSimpleEvents\Tests\Unit
 */

declare(strict_types=1);

namespace MiMe\WPSimpleEvents\Tests\Unit;

use InvalidArgumentException;
use MiMe\WPSimpleEvents\Domain\EventDateRange;
use MiMe\WPSimpleEvents\Domain\EventStatus;
use MiMe\WPSimpleEvents\Occurrence\EventOccurrence;
use MiMe\WPSimpleEvents\Occurrence\OccurrenceSource;
use MiMe\WPSimpleEvents\Occurrence\RecurrenceOccurrenceBuilder;
use MiMe\WPSimpleEvents\Recurrence\OccurrenceExclusion;
use MiMe\WPSimpleEvents\Recurrence\OccurrenceExclusionAction;
use MiMe\WPSimpleEvents\Recurrence\OccurrenceOverride;
use MiMe\WPSimpleEvents\Recurrence\RecurrenceAggregate;
use MiMe\WPSimpleEvents\Recurrence\RecurrenceFollowingExceptionReconciler;
use MiMe\WPSimpleEvents\Recurrence\RecurrenceFollowingMutator;
use MiMe\WPSimpleEvents\Recurrence\RecurrenceGenerationWindow;
use MiMe\WPSimpleEvents\Recurrence\RecurrenceRule;
use MiMe\WPSimpleEvents\Recurrence\ScheduleSegment;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

/**
 * Proves that schedule splits never discard a modified future identity.
 */
#[CoversClass( RecurrenceFollowingExceptionReconciler::class )]
final class RecurrenceFollowingExceptionReconcilerTest extends TestCase {
	private const SERIES_UID = 'a28e5d8c-5237-4b02-97a4-3f8855a3d5ad';

	/**
	 * An orphaned override becomes manual under the same immutable identity.
	 */
	public function test_orphaned_override_is_detached_with_effective_state(): void {
		$identity = '2027-01-04T19:00:00';
		$moved    = $this->range( '2027-01-04T20:00:00', '2027-01-04T22:00:00' );
		$current  = $this->aggregate(
			array(),
			array(
				OccurrenceOverride::from_fields(
					$identity,
					array(
						OccurrenceOverride::DATE_RANGE => $moved,
						OccurrenceOverride::STATUS     => EventStatus::POSTPONED,
					)
				),
			)
		);
		$proposed = $this->replacement( $current );

		$reconciled = ( new RecurrenceFollowingExceptionReconciler() )->reconcile(
			$current,
			$proposed,
			'2027-01-03T19:00:00',
			EventStatus::SCHEDULED
		);

		self::assertCount( 1, $reconciled->manuals );
		self::assertSame( $identity, $reconciled->manuals[0]->recurrence_id );
		self::assertSame( '2027-01-04T20:00:00', $reconciled->manuals[0]->date_range->start_local() );
		self::assertSame( EventStatus::POSTPONED, $reconciled->manuals[0]->status );
		self::assertSame( $current->overrides, $reconciled->overrides );
	}

	/**
	 * A cancellation remains cancelled after detachment and can be restored.
	 */
	public function test_orphaned_cancellation_stays_reversible(): void {
		$identity = '2027-01-04T19:00:00';
		$current  = $this->aggregate(
			array( new OccurrenceExclusion( $identity, OccurrenceExclusionAction::CANCEL ) )
		);
		$proposed = $this->replacement( $current );

		$reconciled = ( new RecurrenceFollowingExceptionReconciler() )->reconcile(
			$current,
			$proposed,
			'2027-01-03T19:00:00',
			EventStatus::SCHEDULED
		);
		$cancelled  = $this->find( $reconciled, $identity );
		$restored   = RecurrenceAggregate::create(
			$reconciled->series_uid,
			$reconciled->timezone,
			$reconciled->segments,
			$reconciled->manuals,
			array(),
			$reconciled->overrides
		);
		$scheduled  = $this->find( $restored, $identity );

		self::assertSame( OccurrenceSource::MANUAL, $cancelled->source );
		self::assertSame( EventStatus::CANCELLED, $cancelled->status );
		self::assertSame( EventStatus::SCHEDULED, $scheduled->status );
		self::assertSame( $cancelled->identity->public_key(), $scheduled->identity->public_key() );
	}

	/**
	 * An exception still generated by the replacement schedule is not detached.
	 */
	public function test_still_generated_exception_remains_sparse(): void {
		$identity = '2027-01-05T19:00:00';
		$current  = $this->aggregate(
			array( new OccurrenceExclusion( $identity, OccurrenceExclusionAction::CANCEL ) )
		);
		$proposed = $this->replacement( $current );

		$reconciled = ( new RecurrenceFollowingExceptionReconciler() )->reconcile(
			$current,
			$proposed,
			'2027-01-03T19:00:00',
			EventStatus::SCHEDULED
		);

		self::assertSame( array(), $reconciled->manuals );
		self::assertSame( $current->exclusions, $reconciled->exclusions );
	}

	/**
	 * Earlier exceptions are immutable and never detached by a future edit.
	 */
	public function test_earlier_exception_is_untouched(): void {
		$identity = '2027-01-02T19:00:00';
		$current  = $this->aggregate(
			array( new OccurrenceExclusion( $identity, OccurrenceExclusionAction::CANCEL ) )
		);
		$proposed = $this->replacement( $current );

		$reconciled = ( new RecurrenceFollowingExceptionReconciler() )->reconcile(
			$current,
			$proposed,
			'2027-01-03T19:00:00',
			EventStatus::SCHEDULED
		);

		self::assertSame( array(), $reconciled->manuals );
		self::assertSame( $current->exclusions, $reconciled->exclusions );
	}

	/**
	 * A client cannot smuggle an exception edit into structural reconciliation.
	 */
	public function test_pre_mutated_exception_collection_is_rejected(): void {
		$current  = $this->aggregate();
		$proposed = $this->replacement( $current );
		$proposed = RecurrenceAggregate::create(
			$proposed->series_uid,
			$proposed->timezone,
			$proposed->segments,
			$proposed->manuals,
			array( new OccurrenceExclusion( '2027-01-04T19:00:00', OccurrenceExclusionAction::CANCEL ) ),
			$proposed->overrides
		);

		$this->expectException( InvalidArgumentException::class );
		( new RecurrenceFollowingExceptionReconciler() )->reconcile(
			$current,
			$proposed,
			'2027-01-03T19:00:00',
			EventStatus::SCHEDULED
		);
	}

	/**
	 * Build one daily aggregate with complete exception state.
	 *
	 * @param array $exclusions Exclusions.
	 * @param array $overrides  Overrides.
	 * @phpstan-param list<OccurrenceExclusion> $exclusions
	 * @phpstan-param list<OccurrenceOverride> $overrides
	 */
	private function aggregate( array $exclusions = array(), array $overrides = array() ): RecurrenceAggregate {
		$root = $this->range( '2027-01-01T19:00:00', '2027-01-01T21:00:00' );

		return RecurrenceAggregate::create(
			self::SERIES_UID,
			'Europe/Brussels',
			array( new ScheduleSegment( 0, $root->start_local(), $root, RecurrenceRule::daily() ) ),
			array(),
			$exclusions,
			$overrides
		);
	}

	/**
	 * Replace the schedule from January 3 with every other day.
	 *
	 * @param RecurrenceAggregate $current Current complete aggregate.
	 */
	private function replacement( RecurrenceAggregate $current ): RecurrenceAggregate {
		return ( new RecurrenceFollowingMutator() )->replace_from(
			$current,
			'2027-01-03T19:00:00',
			$this->range( '2027-01-03T19:00:00', '2027-01-03T21:00:00' ),
			RecurrenceRule::daily( 2 )
		);
	}

	/**
	 * Resolve one occurrence by immutable identity.
	 *
	 * @param RecurrenceAggregate $aggregate Complete recurrence aggregate.
	 * @param string              $identity  Expected immutable identity.
	 * @throws InvalidArgumentException When the expected occurrence is absent.
	 */
	private function find( RecurrenceAggregate $aggregate, string $identity ): EventOccurrence {
		$rows = ( new RecurrenceOccurrenceBuilder() )->build(
			42,
			$aggregate,
			EventStatus::SCHEDULED,
			RecurrenceGenerationWindow::between( '2027-01-01', '2027-01-07', 20 ),
			1
		);

		foreach ( $rows as $row ) {
			if ( $row->identity->recurrence_id() === $identity ) {
				return $row;
			}
		}

		throw new InvalidArgumentException( 'The test occurrence is missing.' );
	}

	/**
	 * Build one timed Brussels range.
	 *
	 * @param string $start Canonical local start.
	 * @param string $end   Canonical local end.
	 */
	private function range( string $start, string $end ): EventDateRange {
		return EventDateRange::from_local( $start, $end, false, 'Europe/Brussels' );
	}
}
